CURRICULUM_5 = [
    {"unit": 1, "lesson": 1, "topic": "Hello", "outcome": "Greet people and introduce yourself using Hello, Hi, Good morning, My name is"},
    {"unit": 1, "lesson": 2, "topic": "Hello", "outcome": "Ask and answer questions about names and ages: What is your name? How old are you?"},
    {"unit": 1, "lesson": 3, "topic": "Hello", "outcome": "Say the alphabet A to Z and spell simple names and words"},
    {"unit": 1, "lesson": 4, "topic": "Hello", "outcome": "Count numbers 1 to 20 and use them in sentences"},
    {"unit": 1, "lesson": 5, "topic": "Hello", "outcome": "Use basic classroom language: Open your book, Listen, Repeat, Stand up, Sit down"},
    {"unit": 1, "lesson": 6, "topic": "Hello", "outcome": "Review and practise Unit 1: greetings, introductions, alphabet, numbers 1-20"},
    {"unit": 2, "lesson": 1, "topic": "My Town", "outcome": "Name places in town: school, park, hospital, market, library, post office"},
    {"unit": 2, "lesson": 2, "topic": "My Town", "outcome": "Ask for and give directions: Turn left, Turn right, Go straight on, It is opposite"},
    {"unit": 2, "lesson": 3, "topic": "My Town", "outcome": "Use Where is the...? and answer with It is next to, near, between, opposite"},
    {"unit": 2, "lesson": 4, "topic": "My Town", "outcome": "Describe your neighbourhood and the places around your home"},
    {"unit": 2, "lesson": 5, "topic": "My Town", "outcome": "Use prepositions of place: in, on, at, next to, between, behind, in front of"},
    {"unit": 2, "lesson": 6, "topic": "My Town", "outcome": "Review and practise Unit 2: places in town, directions, prepositions"},
    {"unit": 3, "lesson": 1, "topic": "Games and Hobbies", "outcome": "Name common hobbies and games: swimming, painting, playing chess, reading"},
    {"unit": 3, "lesson": 2, "topic": "Games and Hobbies", "outcome": "Talk about what you like and dislike: I like, I love, I do not like, I hate + verb-ing"},
    {"unit": 3, "lesson": 3, "topic": "Games and Hobbies", "outcome": "Use I like/love/enjoy + verb-ing correctly in sentences"},
    {"unit": 3, "lesson": 4, "topic": "Games and Hobbies", "outcome": "Ask about others hobbies: Do you like...? What do you like doing?"},
    {"unit": 3, "lesson": 5, "topic": "Games and Hobbies", "outcome": "Answer with Yes, I do and No, I do not and give reasons"},
    {"unit": 3, "lesson": 6, "topic": "Games and Hobbies", "outcome": "Review and practise Unit 3: hobbies, likes and dislikes, asking and answering"},
    {"unit": 4, "lesson": 1, "topic": "My Body", "outcome": "Name body parts: head, shoulders, knees, toes, eyes, ears, mouth, nose"},
    {"unit": 4, "lesson": 2, "topic": "My Body", "outcome": "Describe physical appearance: tall, short, thin, curly hair, blue eyes"},
    {"unit": 4, "lesson": 3, "topic": "My Body", "outcome": "Use He has got and She has got to describe people appearance"},
    {"unit": 4, "lesson": 4, "topic": "My Body", "outcome": "Talk about health problems: I have got a headache, stomachache, toothache, cold"},
    {"unit": 4, "lesson": 5, "topic": "My Body", "outcome": "Give simple health advice: You should rest, drink water, see a doctor"},
    {"unit": 4, "lesson": 6, "topic": "My Body", "outcome": "Review and practise Unit 4: body parts, appearance, health problems, advice"},
    {"unit": 5, "lesson": 1, "topic": "Cooking", "outcome": "Name common foods and ingredients: flour, egg, sugar, butter, milk, vegetables"},
    {"unit": 5, "lesson": 2, "topic": "Cooking", "outcome": "Understand countable and uncountable nouns with food vocabulary"},
    {"unit": 5, "lesson": 3, "topic": "Cooking", "outcome": "Use some and any correctly: Is there any milk? Yes, there is some milk"},
    {"unit": 5, "lesson": 4, "topic": "Cooking", "outcome": "Follow simple recipe instructions using imperative forms: add, mix, cut, boil, stir"},
    {"unit": 5, "lesson": 5, "topic": "Cooking", "outcome": "Talk about favourite foods and describe simple meals"},
    {"unit": 5, "lesson": 6, "topic": "Cooking", "outcome": "Review and practise Unit 5: food vocabulary, some and any, recipe instructions"},
    {"unit": 6, "lesson": 1, "topic": "Emotions", "outcome": "Name basic emotions: happy, sad, angry, scared, surprised, bored, excited, tired"},
    {"unit": 6, "lesson": 2, "topic": "Emotions", "outcome": "Ask and answer How do you feel? and respond with I feel + adjective"},
    {"unit": 6, "lesson": 3, "topic": "Emotions", "outcome": "Describe why you feel a certain way: I feel happy because it is my birthday"},
    {"unit": 6, "lesson": 4, "topic": "Emotions", "outcome": "Use adjectives to describe feelings in sentences about daily situations"},
    {"unit": 6, "lesson": 5, "topic": "Emotions", "outcome": "Talk about situations that cause emotions and use I feel... because..."},
    {"unit": 6, "lesson": 6, "topic": "Emotions", "outcome": "Review and practise Unit 6: emotions vocabulary, asking and describing feelings"},
    {"unit": 7, "lesson": 1, "topic": "Movie Time", "outcome": "Name movie genres: action, comedy, horror, animation, drama, science fiction"},
    {"unit": 7, "lesson": 2, "topic": "Movie Time", "outcome": "Express opinions about movies using I think, I believe, In my opinion"},
    {"unit": 7, "lesson": 3, "topic": "Movie Time", "outcome": "Talk about favourite actors and movies using simple present tense"},
    {"unit": 7, "lesson": 4, "topic": "Movie Time", "outcome": "Describe movie plots using simple present: The story is about, The main character"},
    {"unit": 7, "lesson": 5, "topic": "Movie Time", "outcome": "Ask and answer questions about movies: What is your favourite movie? Who is your favourite actor?"},
    {"unit": 7, "lesson": 6, "topic": "Movie Time", "outcome": "Review and practise Unit 7: movie genres, opinions, describing plots"},
    {"unit": 8, "lesson": 1, "topic": "Seasons and Weather", "outcome": "Name the four seasons: spring, summer, autumn, winter and their characteristics"},
    {"unit": 8, "lesson": 2, "topic": "Seasons and Weather", "outcome": "Describe weather conditions using It is sunny, rainy, snowy, windy, cloudy, foggy"},
    {"unit": 8, "lesson": 3, "topic": "Seasons and Weather", "outcome": "Use What is the weather like? and answer with full sentences"},
    {"unit": 8, "lesson": 4, "topic": "Seasons and Weather", "outcome": "Talk about activities in different seasons: In summer I go swimming, In winter I build snowmen"},
    {"unit": 8, "lesson": 5, "topic": "Seasons and Weather", "outcome": "Use present continuous for current weather: It is raining now, The sun is shining"},
    {"unit": 8, "lesson": 6, "topic": "Seasons and Weather", "outcome": "Review and practise Unit 8: seasons, weather vocabulary, activities"},
]

CURRICULUM_6 = [
    {"unit": 1, "lesson": 1, "topic": "Life", "outcome": "Describe daily routines using simple present: I wake up at 7, I have breakfast, I go to school"},
    {"unit": 1, "lesson": 2, "topic": "Life", "outcome": "Tell the time and talk about schedules: It is half past eight, My lesson starts at nine"},
    {"unit": 1, "lesson": 3, "topic": "Life", "outcome": "Use frequency adverbs: always, usually, often, sometimes, rarely, never"},
    {"unit": 1, "lesson": 4, "topic": "Life", "outcome": "Ask and answer about daily habits: What time do you wake up? What do you do after school?"},
    {"unit": 1, "lesson": 5, "topic": "Life", "outcome": "Describe weekend activities and compare them to weekday routines"},
    {"unit": 1, "lesson": 6, "topic": "Life", "outcome": "Review and practise Unit 1: daily routines, telling the time, frequency adverbs"},
    {"unit": 2, "lesson": 1, "topic": "Celebrations", "outcome": "Name celebrations and festivals: birthday, New Year, national holiday, Eid, harvest festival"},
    {"unit": 2, "lesson": 2, "topic": "Celebrations", "outcome": "Describe how people celebrate: They eat special food, They wear traditional clothes, They dance"},
    {"unit": 2, "lesson": 3, "topic": "Celebrations", "outcome": "Use present continuous to describe celebrations happening now: People are dancing and singing"},
    {"unit": 2, "lesson": 4, "topic": "Celebrations", "outcome": "Write and say greetings for special occasions: Happy Birthday, Happy New Year, Congratulations"},
    {"unit": 2, "lesson": 5, "topic": "Celebrations", "outcome": "Compare celebrations in Turkey and other countries using but and however"},
    {"unit": 2, "lesson": 6, "topic": "Celebrations", "outcome": "Review and practise Unit 2: festivals, celebrations vocabulary, greetings"},
    {"unit": 3, "lesson": 1, "topic": "My Environment", "outcome": "Describe natural features: mountains, rivers, forests, plains, coasts, lakes"},
    {"unit": 3, "lesson": 2, "topic": "My Environment", "outcome": "Talk about environmental problems: pollution, deforestation, litter, waste"},
    {"unit": 3, "lesson": 3, "topic": "My Environment", "outcome": "Use should and should not to give advice about protecting the environment"},
    {"unit": 3, "lesson": 4, "topic": "My Environment", "outcome": "Describe your local environment and what you love about where you live"},
    {"unit": 3, "lesson": 5, "topic": "My Environment", "outcome": "Talk about ways to help the environment: recycle, save water, plant trees, use less plastic"},
    {"unit": 3, "lesson": 6, "topic": "My Environment", "outcome": "Review and practise Unit 3: environment vocabulary, giving advice with should"},
    {"unit": 4, "lesson": 1, "topic": "Food and Restaurants", "outcome": "Read a menu and name dishes: starter, main course, dessert, drink"},
    {"unit": 4, "lesson": 2, "topic": "Food and Restaurants", "outcome": "Order food politely: I would like, Could I have, What do you recommend?"},
    {"unit": 4, "lesson": 3, "topic": "Food and Restaurants", "outcome": "Use much and many: How much sugar? How many eggs? There is not much time"},
    {"unit": 4, "lesson": 4, "topic": "Food and Restaurants", "outcome": "Describe tastes and textures: sweet, salty, sour, spicy, crunchy, soft, delicious"},
    {"unit": 4, "lesson": 5, "topic": "Food and Restaurants", "outcome": "Have a restaurant dialogue: greet customers, take orders, ask for the bill"},
    {"unit": 4, "lesson": 6, "topic": "Food and Restaurants", "outcome": "Review and practise Unit 4: restaurant vocabulary, ordering food, much and many"},
    {"unit": 5, "lesson": 1, "topic": "Sports", "outcome": "Name sports and equipment: football, basketball, swimming, tennis racket, goalkeeper"},
    {"unit": 5, "lesson": 2, "topic": "Sports", "outcome": "Talk about sports using play, go, do: I play basketball, I go swimming, I do gymnastics"},
    {"unit": 5, "lesson": 3, "topic": "Sports", "outcome": "Use simple past to talk about past sports events: They played, She scored, He won"},
    {"unit": 5, "lesson": 4, "topic": "Sports", "outcome": "Describe a sports match: The score was, The team won by two goals, It was an exciting game"},
    {"unit": 5, "lesson": 5, "topic": "Sports", "outcome": "Talk about your favourite sports star and why you admire them"},
    {"unit": 5, "lesson": 6, "topic": "Sports", "outcome": "Review and practise Unit 5: sports vocabulary, play/go/do, simple past"},
    {"unit": 6, "lesson": 1, "topic": "Occupations", "outcome": "Name jobs and say what people do: A doctor treats patients, A teacher teaches students"},
    {"unit": 6, "lesson": 2, "topic": "Occupations", "outcome": "Talk about workplace and tools: A chef works in a kitchen and uses knives and pans"},
    {"unit": 6, "lesson": 3, "topic": "Occupations", "outcome": "Use want to be and would like to be to talk about future jobs: I want to be an engineer"},
    {"unit": 6, "lesson": 4, "topic": "Occupations", "outcome": "Describe skills and qualities needed for jobs: You need to be patient, creative, hardworking"},
    {"unit": 6, "lesson": 5, "topic": "Occupations", "outcome": "Ask and answer about jobs: What does your mother do? Where does she work?"},
    {"unit": 6, "lesson": 6, "topic": "Occupations", "outcome": "Review and practise Unit 6: jobs vocabulary, describing roles, future plans"},
    {"unit": 7, "lesson": 1, "topic": "Movies", "outcome": "Name film genres and describe them: An action film is exciting, A comedy makes you laugh"},
    {"unit": 7, "lesson": 2, "topic": "Movies", "outcome": "Give opinions about films: I think it was brilliant, I found it boring, The acting was great"},
    {"unit": 7, "lesson": 3, "topic": "Movies", "outcome": "Use comparative adjectives: more exciting than, funnier than, scarier than"},
    {"unit": 7, "lesson": 4, "topic": "Movies", "outcome": "Describe a film plot using past simple: The story was about, The hero saved, In the end"},
    {"unit": 7, "lesson": 5, "topic": "Movies", "outcome": "Recommend a film and explain why someone should watch it"},
    {"unit": 7, "lesson": 6, "topic": "Movies", "outcome": "Review and practise Unit 7: film genres, opinions, comparative adjectives"},
    {"unit": 8, "lesson": 1, "topic": "Music", "outcome": "Name music genres: pop, rock, classical, jazz, folk, hip hop, electronic"},
    {"unit": 8, "lesson": 2, "topic": "Music", "outcome": "Name instruments and say who plays them: a guitarist plays the guitar, a pianist plays the piano"},
    {"unit": 8, "lesson": 3, "topic": "Music", "outcome": "Talk about music preferences using like, love, prefer, cannot stand"},
    {"unit": 8, "lesson": 4, "topic": "Music", "outcome": "Use superlative adjectives: the best song, the most popular band, the greatest musician"},
    {"unit": 8, "lesson": 5, "topic": "Music", "outcome": "Describe your favourite musician or band and explain what makes their music special"},
    {"unit": 8, "lesson": 6, "topic": "Music", "outcome": "Review and practise Unit 8: music genres, instruments, superlatives"},
]
CURRICULUM_7 = [
    {"unit": 1, "lesson": 1, "topic": "Appearance and Personality", "outcome": "Describe physical appearance using adjectives: tall, slim, curly-haired, blonde, dark-skinned"},
    {"unit": 1, "lesson": 2, "topic": "Appearance and Personality", "outcome": "Describe personality traits: friendly, clever, brave, shy, generous, selfish, honest"},
    {"unit": 1, "lesson": 3, "topic": "Appearance and Personality", "outcome": "Use He/She looks + adjective and He/She seems + adjective to describe people"},
    {"unit": 1, "lesson": 4, "topic": "Appearance and Personality", "outcome": "Compare people using comparative adjectives: taller than, more friendly than"},
    {"unit": 1, "lesson": 5, "topic": "Appearance and Personality", "outcome": "Write a short paragraph describing a friend's appearance and personality"},
    {"unit": 1, "lesson": 6, "topic": "Appearance and Personality", "outcome": "Review and practise Unit 1: appearance, personality, comparatives"},
    {"unit": 2, "lesson": 1, "topic": "Sports", "outcome": "Name sports and equipment: football, basketball, tennis racket, swimming goggles, volleyball"},
    {"unit": 2, "lesson": 2, "topic": "Sports", "outcome": "Talk about sports you play using I play, I do, I go + sport"},
    {"unit": 2, "lesson": 3, "topic": "Sports", "outcome": "Use adverbs of frequency: always, usually, often, sometimes, rarely, never with sports"},
    {"unit": 2, "lesson": 4, "topic": "Sports", "outcome": "Discuss sporting events and competitions: tournament, championship, medal, referee, score"},
    {"unit": 2, "lesson": 5, "topic": "Sports", "outcome": "Express ability with can and cannot: I can swim but I cannot ski"},
    {"unit": 2, "lesson": 6, "topic": "Sports", "outcome": "Review and practise Unit 2: sports vocabulary, frequency adverbs, ability"},
    {"unit": 3, "lesson": 1, "topic": "Biographies", "outcome": "Talk about past events using simple past tense: was, were, lived, worked, studied"},
    {"unit": 3, "lesson": 2, "topic": "Biographies", "outcome": "Use time expressions with past tense: in 1990, last year, ago, when, after"},
    {"unit": 3, "lesson": 3, "topic": "Biographies", "outcome": "Read and understand a short biography of a famous person"},
    {"unit": 3, "lesson": 4, "topic": "Biographies", "outcome": "Ask and answer questions about the past: When did he/she...? Where did he/she...?"},
    {"unit": 3, "lesson": 5, "topic": "Biographies", "outcome": "Write a short biography using past tense and time connectors: first, then, finally"},
    {"unit": 3, "lesson": 6, "topic": "Biographies", "outcome": "Review and practise Unit 3: simple past tense, biographies, time expressions"},
    {"unit": 4, "lesson": 1, "topic": "Wild Animals", "outcome": "Name wild animals and their habitats: lion, elephant, eagle, dolphin, rainforest, savannah"},
    {"unit": 4, "lesson": 2, "topic": "Wild Animals", "outcome": "Describe animals using have got, can, eat: Eagles have got sharp claws and can fly"},
    {"unit": 4, "lesson": 3, "topic": "Wild Animals", "outcome": "Use superlative adjectives: the biggest, the fastest, the most dangerous animal"},
    {"unit": 4, "lesson": 4, "topic": "Wild Animals", "outcome": "Discuss endangered animals and conservation: extinct, protect, habitat, wildlife"},
    {"unit": 4, "lesson": 5, "topic": "Wild Animals", "outcome": "Read and understand a short text about an animal and answer comprehension questions"},
    {"unit": 4, "lesson": 6, "topic": "Wild Animals", "outcome": "Review and practise Unit 4: animal vocabulary, superlatives, conservation"},
    {"unit": 5, "lesson": 1, "topic": "Television and Social Media", "outcome": "Name TV programme types: documentary, news, cartoon, reality show, soap opera"},
    {"unit": 5, "lesson": 2, "topic": "Television and Social Media", "outcome": "Talk about social media platforms and activities: post, share, follow, like, comment"},
    {"unit": 5, "lesson": 3, "topic": "Television and Social Media", "outcome": "Express opinions about media: I think it is entertaining, boring, educational, harmful"},
    {"unit": 5, "lesson": 4, "topic": "Television and Social Media", "outcome": "Use present continuous for current actions: She is watching a documentary right now"},
    {"unit": 5, "lesson": 5, "topic": "Television and Social Media", "outcome": "Discuss screen time and digital well-being: spend time, addicted, balance, limit"},
    {"unit": 5, "lesson": 6, "topic": "Television and Social Media", "outcome": "Review and practise Unit 5: media vocabulary, opinions, present continuous"},
    {"unit": 6, "lesson": 1, "topic": "Celebrations", "outcome": "Name celebrations and festivals: New Year, birthday, national holiday, harvest festival"},
    {"unit": 6, "lesson": 2, "topic": "Celebrations", "outcome": "Describe celebration activities: decorate, gather, exchange gifts, wear costumes, watch fireworks"},
    {"unit": 6, "lesson": 3, "topic": "Celebrations", "outcome": "Use going to for future plans: We are going to celebrate, I am going to buy a gift"},
    {"unit": 6, "lesson": 4, "topic": "Celebrations", "outcome": "Talk about Turkish celebrations: Republic Day, Eid, Children's Day, Victory Day"},
    {"unit": 6, "lesson": 5, "topic": "Celebrations", "outcome": "Write an invitation for a celebration including date, time, place, and activity"},
    {"unit": 6, "lesson": 6, "topic": "Celebrations", "outcome": "Review and practise Unit 6: celebration vocabulary, going to future, invitations"},
    {"unit": 7, "lesson": 1, "topic": "Natural Forces", "outcome": "Name natural disasters and weather events: earthquake, flood, tornado, tsunami, drought"},
    {"unit": 7, "lesson": 2, "topic": "Natural Forces", "outcome": "Describe the effects of natural disasters using past tense: destroyed, flooded, damaged"},
    {"unit": 7, "lesson": 3, "topic": "Natural Forces", "outcome": "Use should and must for safety advice: You should move to higher ground, You must stay calm"},
    {"unit": 7, "lesson": 4, "topic": "Natural Forces", "outcome": "Understand an emergency announcement and follow safety instructions"},
    {"unit": 7, "lesson": 5, "topic": "Natural Forces", "outcome": "Talk about climate change and its connection to natural disasters"},
    {"unit": 7, "lesson": 6, "topic": "Natural Forces", "outcome": "Review and practise Unit 7: natural disasters, safety advice, should and must"},
    {"unit": 8, "lesson": 1, "topic": "Inventions", "outcome": "Name important inventions: printing press, telephone, electricity, internet, vaccine"},
    {"unit": 8, "lesson": 2, "topic": "Inventions", "outcome": "Use passive voice in simple past: The telephone was invented by Alexander Graham Bell"},
    {"unit": 8, "lesson": 3, "topic": "Inventions", "outcome": "Talk about the impact of inventions on daily life using changed, improved, made easier"},
    {"unit": 8, "lesson": 4, "topic": "Inventions", "outcome": "Express opinions about technology: I believe that, In my opinion, It seems to me that"},
    {"unit": 8, "lesson": 5, "topic": "Inventions", "outcome": "Describe a simple invention: what it does, who invented it, why it is important"},
    {"unit": 8, "lesson": 6, "topic": "Inventions", "outcome": "Review and practise Unit 8: inventions vocabulary, passive voice, expressing opinions"},
]

CURRICULUM_LGS = [
    {"unit": 1, "lesson": 1, "topic": "Friendship", "outcome": "Describe qualities of a good friend using adjectives and give examples from real life"},
    {"unit": 1, "lesson": 2, "topic": "Friendship", "outcome": "Use relative clauses with who to describe people: A friend is someone who supports you"},
    {"unit": 1, "lesson": 3, "topic": "Friendship", "outcome": "Express agreement and disagreement politely: I agree, I see your point, However I think"},
    {"unit": 1, "lesson": 4, "topic": "Friendship", "outcome": "Read a dialogue about friendship and identify main ideas and supporting details"},
    {"unit": 1, "lesson": 5, "topic": "Friendship", "outcome": "Write a paragraph about your best friend using descriptive language and examples"},
    {"unit": 1, "lesson": 6, "topic": "Friendship", "outcome": "Review and practise Unit 1: friendship vocabulary, relative clauses, opinion expressions"},
    {"unit": 2, "lesson": 1, "topic": "Teen Life", "outcome": "Discuss typical activities and concerns of teenagers using present simple and continuous"},
    {"unit": 2, "lesson": 2, "topic": "Teen Life", "outcome": "Use have to and do not have to to talk about obligations and freedoms in daily life"},
    {"unit": 2, "lesson": 3, "topic": "Teen Life", "outcome": "Talk about problems teenagers face: peer pressure, social media, study stress"},
    {"unit": 2, "lesson": 4, "topic": "Teen Life", "outcome": "Give and respond to advice using You should, Why do not you, Have you tried"},
    {"unit": 2, "lesson": 5, "topic": "Teen Life", "outcome": "Read a magazine article about teen life and answer multiple choice questions"},
    {"unit": 2, "lesson": 6, "topic": "Teen Life", "outcome": "Review and practise Unit 2: teen vocabulary, have to, giving advice"},
    {"unit": 3, "lesson": 1, "topic": "Cooking", "outcome": "Describe complex recipes using sequencing words: first, then, after that, finally, once"},
    {"unit": 3, "lesson": 2, "topic": "Cooking", "outcome": "Use quantifiers accurately: a few, a little, plenty of, a large amount of, several"},
    {"unit": 3, "lesson": 3, "topic": "Cooking", "outcome": "Discuss food culture and traditional Turkish dishes with descriptive vocabulary"},
    {"unit": 3, "lesson": 4, "topic": "Cooking", "outcome": "Understand and use conditional sentences: If you add too much salt, it will taste bitter"},
    {"unit": 3, "lesson": 5, "topic": "Cooking", "outcome": "Write a recipe including ingredients list and numbered method steps"},
    {"unit": 3, "lesson": 6, "topic": "Cooking", "outcome": "Review and practise Unit 3: cooking vocabulary, quantifiers, conditionals"},
    {"unit": 4, "lesson": 1, "topic": "Communication", "outcome": "Identify different ways people communicate: verbal, non-verbal, written, digital"},
    {"unit": 4, "lesson": 2, "topic": "Communication", "outcome": "Use reported speech to relay information: She said that, He told me that, They asked whether"},
    {"unit": 4, "lesson": 3, "topic": "Communication", "outcome": "Discuss barriers to communication: language, culture, noise, misunderstanding"},
    {"unit": 4, "lesson": 4, "topic": "Communication", "outcome": "Practise formal and informal communication: emails, messages, presentations"},
    {"unit": 4, "lesson": 5, "topic": "Communication", "outcome": "Read a text about communication technology and identify the writer's purpose"},
    {"unit": 4, "lesson": 6, "topic": "Communication", "outcome": "Review and practise Unit 4: communication vocabulary, reported speech, register"},
    {"unit": 5, "lesson": 1, "topic": "The Environment", "outcome": "Identify environmental problems: deforestation, pollution, global warming, species loss"},
    {"unit": 5, "lesson": 2, "topic": "The Environment", "outcome": "Use the first conditional for real environmental scenarios: If we recycle more, we will reduce waste"},
    {"unit": 5, "lesson": 3, "topic": "The Environment", "outcome": "Discuss causes and effects of climate change using because, therefore, as a result"},
    {"unit": 5, "lesson": 4, "topic": "The Environment", "outcome": "Talk about solutions to environmental problems: renewable energy, reforestation, carbon footprint"},
    {"unit": 5, "lesson": 5, "topic": "The Environment", "outcome": "Read an environmental report and distinguish between facts and opinions"},
    {"unit": 5, "lesson": 6, "topic": "The Environment", "outcome": "Review and practise Unit 5: environment vocabulary, first conditional, cause and effect"},
    {"unit": 6, "lesson": 1, "topic": "Bridging Cultures", "outcome": "Compare cultural practices around the world: greetings, celebrations, food, family roles"},
    {"unit": 6, "lesson": 2, "topic": "Bridging Cultures", "outcome": "Use the second conditional for hypothetical cultural situations: If I lived in Japan, I would"},
    {"unit": 6, "lesson": 3, "topic": "Bridging Cultures", "outcome": "Discuss stereotypes and cultural sensitivity: avoid generalisations, show respect"},
    {"unit": 6, "lesson": 4, "topic": "Bridging Cultures", "outcome": "Understand idioms and expressions used in different English-speaking cultures"},
    {"unit": 6, "lesson": 5, "topic": "Bridging Cultures", "outcome": "Write a comparison paragraph about two cultural practices using linking words"},
    {"unit": 6, "lesson": 6, "topic": "Bridging Cultures", "outcome": "Review and practise Unit 6: culture vocabulary, second conditional, comparison writing"},
    {"unit": 7, "lesson": 1, "topic": "Science and Technology", "outcome": "Discuss scientific discoveries and their impact using passive voice constructions"},
    {"unit": 7, "lesson": 2, "topic": "Science and Technology", "outcome": "Use will and might for future predictions about technology: Robots will replace some jobs"},
    {"unit": 7, "lesson": 3, "topic": "Science and Technology", "outcome": "Understand technical vocabulary in context: artificial intelligence, gene editing, space exploration"},
    {"unit": 7, "lesson": 4, "topic": "Science and Technology", "outcome": "Read a science article and answer inference questions requiring understanding beyond literal meaning"},
    {"unit": 7, "lesson": 5, "topic": "Science and Technology", "outcome": "Express enthusiasm, doubt, and concern about new technologies using appropriate language"},
    {"unit": 7, "lesson": 6, "topic": "Science and Technology", "outcome": "Review and practise Unit 7: science vocabulary, future tenses, passive voice"},
    {"unit": 8, "lesson": 1, "topic": "Chores and Responsibilities", "outcome": "Discuss household chores and family responsibilities using present simple and have to"},
    {"unit": 8, "lesson": 2, "topic": "Chores and Responsibilities", "outcome": "Negotiate and compromise using language like: How about, What if, That seems fair"},
    {"unit": 8, "lesson": 3, "topic": "Chores and Responsibilities", "outcome": "Talk about personal responsibilities at school, home, and in the community"},
    {"unit": 8, "lesson": 4, "topic": "Chores and Responsibilities", "outcome": "Use modal verbs for obligation and permission: must, should, can, may, need to"},
    {"unit": 8, "lesson": 5, "topic": "Chores and Responsibilities", "outcome": "Read a short story about responsibility and identify the moral lesson"},
    {"unit": 8, "lesson": 6, "topic": "Chores and Responsibilities", "outcome": "Review and practise Unit 8: responsibility vocabulary, modal verbs, negotiation language"},
]


def get_lesson(video_number: int, grade: int = 5) -> dict:
    curriculum = {5: CURRICULUM_5, 6: CURRICULUM_6, 7: CURRICULUM_7, 8: CURRICULUM_LGS}[grade]
    idx = (video_number - 1) % len(curriculum)
    lesson = curriculum[idx]
    return {
        "unit": lesson["unit"],
        "lesson": lesson["lesson"],
        "topic": lesson["topic"],
        "outcome": lesson["outcome"],
        "video_number": video_number,
    }


CURRICULUM = CURRICULUM_5