CURRICULUM = [
    {"unit": 1, "lesson": 1, "topic": "Hello", "outcome": "Greet people and introduce yourself using Hello, Hi, Good morning, My name is"},
    {"unit": 1, "lesson": 2, "topic": "Hello", "outcome": "Ask and answer questions about names and ages: What is your name? How old are you?"},
    {"unit": 1, "lesson": 3, "topic": "Hello", "outcome": "Say the alphabet A to Z and spell simple names and words"},
    {"unit": 1, "lesson": 4, "topic": "Hello", "outcome": "Count numbers 1 to 20 and use them in sentences"},
    {"unit": 1, "lesson": 5, "topic": "Hello", "outcome": "Use basic classroom language: Open your book, Listen, Repeat, Stand up, Sit down"},
    {"unit": 1, "lesson": 6, "topic": "Hello", "outcome": "Review and practise Unit 1: greetings, introductions, alphabet, numbers 1-20"},
    {"unit": 2, "lesson": 1, "topic": "My Town", "outcome": "Name places in town: school, park, hospital, market, library, post office"},
    {"unit": 2, "lesson": 2, "topic": "My Town", "outcome": "Ask for and give directions: Turn left, Turn right, Go straight on, It is opposite"},
    {"unit": 2, "lesson": 3, "topic": "My Town", "outcome": "Use Where is the...? and answer with It is next to, near, between, opposite"},
    {"unit": 2, "lesson": 4, "topic": "My Town", "outcome": "Describe your neighbourhood and the places around your home"},
    {"unit": 2, "lesson": 5, "topic": "My Town", "outcome": "Use prepositions of place: in, on, at, next to, between, behind, in front of"},
    {"unit": 2, "lesson": 6, "topic": "My Town", "outcome": "Review and practise Unit 2: places in town, directions, prepositions"},
    {"unit": 3, "lesson": 1, "topic": "Games and Hobbies", "outcome": "Name common hobbies and games: swimming, painting, playing chess, reading"},
    {"unit": 3, "lesson": 2, "topic": "Games and Hobbies", "outcome": "Talk about what you like and dislike: I like, I love, I do not like, I hate + verb-ing"},
    {"unit": 3, "lesson": 3, "topic": "Games and Hobbies", "outcome": "Use I like/love/enjoy + verb-ing correctly in sentences"},
    {"unit": 3, "lesson": 4, "topic": "Games and Hobbies", "outcome": "Ask about others hobbies: Do you like...? What do you like doing?"},
    {"unit": 3, "lesson": 5, "topic": "Games and Hobbies", "outcome": "Answer with Yes, I do and No, I do not and give reasons"},
    {"unit": 3, "lesson": 6, "topic": "Games and Hobbies", "outcome": "Review and practise Unit 3: hobbies, likes and dislikes, asking and answering"},
    {"unit": 4, "lesson": 1, "topic": "My Body", "outcome": "Name body parts: head, shoulders, knees, toes, eyes, ears, mouth, nose"},
    {"unit": 4, "lesson": 2, "topic": "My Body", "outcome": "Describe physical appearance: tall, short, thin, curly hair, blue eyes"},
    {"unit": 4, "lesson": 3, "topic": "My Body", "outcome": "Use He has got and She has got to describe people appearance"},
    {"unit": 4, "lesson": 4, "topic": "My Body", "outcome": "Talk about health problems: I have got a headache, stomachache, toothache, cold"},
    {"unit": 4, "lesson": 5, "topic": "My Body", "outcome": "Give simple health advice: You should rest, drink water, see a doctor"},
    {"unit": 4, "lesson": 6, "topic": "My Body", "outcome": "Review and practise Unit 4: body parts, appearance, health problems, advice"},
    {"unit": 5, "lesson": 1, "topic": "Cooking", "outcome": "Name common foods and ingredients: flour, egg, sugar, butter, milk, vegetables"},
    {"unit": 5, "lesson": 2, "topic": "Cooking", "outcome": "Understand countable and uncountable nouns with food vocabulary"},
    {"unit": 5, "lesson": 3, "topic": "Cooking", "outcome": "Use some and any correctly: Is there any milk? Yes, there is some milk"},
    {"unit": 5, "lesson": 4, "topic": "Cooking", "outcome": "Follow simple recipe instructions using imperative forms: add, mix, cut, boil, stir"},
    {"unit": 5, "lesson": 5, "topic": "Cooking", "outcome": "Talk about favourite foods and describe simple meals"},
    {"unit": 5, "lesson": 6, "topic": "Cooking", "outcome": "Review and practise Unit 5: food vocabulary, some and any, recipe instructions"},
    {"unit": 6, "lesson": 1, "topic": "Emotions", "outcome": "Name basic emotions: happy, sad, angry, scared, surprised, bored, excited, tired"},
    {"unit": 6, "lesson": 2, "topic": "Emotions", "outcome": "Ask and answer How do you feel? and respond with I feel + adjective"},
    {"unit": 6, "lesson": 3, "topic": "Emotions", "outcome": "Describe why you feel a certain way: I feel happy because it is my birthday"},
    {"unit": 6, "lesson": 4, "topic": "Emotions", "outcome": "Use adjectives to describe feelings in sentences about daily situations"},
    {"unit": 6, "lesson": 5, "topic": "Emotions", "outcome": "Talk about situations that cause emotions and use I feel... because..."},
    {"unit": 6, "lesson": 6, "topic": "Emotions", "outcome": "Review and practise Unit 6: emotions vocabulary, asking and describing feelings"},
    {"unit": 7, "lesson": 1, "topic": "Movie Time", "outcome": "Name movie genres: action, comedy, horror, animation, drama, science fiction"},
    {"unit": 7, "lesson": 2, "topic": "Movie Time", "outcome": "Express opinions about movies using I think, I believe, In my opinion"},
    {"unit": 7, "lesson": 3, "topic": "Movie Time", "outcome": "Talk about favourite actors and movies using simple present tense"},
    {"unit": 7, "lesson": 4, "topic": "Movie Time", "outcome": "Describe movie plots using simple present: The story is about, The main character"},
    {"unit": 7, "lesson": 5, "topic": "Movie Time", "outcome": "Ask and answer questions about movies: What is your favourite movie? Who is your favourite actor?"},
    {"unit": 7, "lesson": 6, "topic": "Movie Time", "outcome": "Review and practise Unit 7: movie genres, opinions, describing plots"},
    {"unit": 8, "lesson": 1, "topic": "Seasons and Weather", "outcome": "Name the four seasons: spring, summer, autumn, winter and their characteristics"},
    {"unit": 8, "lesson": 2, "topic": "Seasons and Weather", "outcome": "Describe weather conditions using It is sunny, rainy, snowy, windy, cloudy, foggy"},
    {"unit": 8, "lesson": 3, "topic": "Seasons and Weather", "outcome": "Use What is the weather like? and answer with full sentences"},
    {"unit": 8, "lesson": 4, "topic": "Seasons and Weather", "outcome": "Talk about activities in different seasons: In summer I go swimming, In winter I build snowmen"},
    {"unit": 8, "lesson": 5, "topic": "Seasons and Weather", "outcome": "Use present continuous for current weather: It is raining now, The sun is shining"},
    {"unit": 8, "lesson": 6, "topic": "Seasons and Weather", "outcome": "Review and practise Unit 8: seasons, weather vocabulary, activities"},
]


def get_lesson(video_number: int) -> dict:
    idx = (video_number - 1) % len(CURRICULUM)
    lesson = CURRICULUM[idx]
    return {
        "unit": lesson["unit"],
        "lesson": lesson["lesson"],
        "topic": lesson["topic"],
        "outcome": lesson["outcome"],
        "video_number": video_number,
    }
