CURRICULUM_5 = [
    {"unit": 1, "lesson": 1, "topic": "Hello", "outcome": "Greet people and introduce yourself using Hello, Hi, Good morning, My name is"},
    {"unit": 1, "lesson": 2, "topic": "Hello", "outcome": "Ask and answer questions about names and ages: What is your name? How old are you?"},
    {"unit": 1, "lesson": 3, "topic": "Hello", "outcome": "Say the alphabet A to Z and spell simple names and words"},
    {"unit": 1, "lesson": 4, "topic": "Hello", "outcome": "Count numbers 1 to 20 and use them in sentences"},
    {"unit": 1, "lesson": 5, "topic": "Hello", "outcome": "Use basic classroom language: Open your book, Listen, Repeat, Stand up, Sit down"},
    {"unit": 1, "lesson": 6, "topic": "Hello", "outcome": "Review and practise Unit 1: greetings, introductions, alphabet, numbers 1-20"},
    {"unit": 2, "lesson": 1, "topic": "My Town", "outcome": "Name places in town: school, park, hospital, market, library, post office"},
    {"unit": 2, "lesson": 2, "topic": "My Town", "outcome": "Ask for and give directions: Turn left, Turn right, Go straight on, It is opposite"},
    {"unit": 2, "lesson": 3, "topic": "My Town", "outcome": "Use Where is the...? and answer with It is next to, near, between, opposite"},
    {"unit": 2, "lesson": 4, "topic": "My Town", "outcome": "Describe your neighbourhood and the places around your home"},
    {"unit": 2, "lesson": 5, "topic": "My Town", "outcome": "Use prepositions of place: in, on, at, next to, between, behind, in front of"},
    {"unit": 2, "lesson": 6, "topic": "My Town", "outcome": "Review and practise Unit 2: places in town, directions, prepositions"},
    {"unit": 3, "lesson": 1, "topic": "Games and Hobbies", "outcome": "Name common hobbies and games: swimming, painting, playing chess, reading"},
    {"unit": 3, "lesson": 2, "topic": "Games and Hobbies", "outcome": "Talk about what you like and dislike: I like, I love, I do not like, I hate + verb-ing"},
    {"unit": 3, "lesson": 3, "topic": "Games and Hobbies", "outcome": "Use I like/love/enjoy + verb-ing correctly in sentences"},
    {"unit": 3, "lesson": 4, "topic": "Games and Hobbies", "outcome": "Ask about others hobbies: Do you like...? What do you like doing?"},
    {"unit": 3, "lesson": 5, "topic": "Games and Hobbies", "outcome": "Answer with Yes, I do and No, I do not and give reasons"},
    {"unit": 3, "lesson": 6, "topic": "Games and Hobbies", "outcome": "Review and practise Unit 3: hobbies, likes and dislikes, asking and answering"},
    {"unit": 4, "lesson": 1, "topic": "My Body", "outcome": "Name body parts: head, shoulders, knees, toes, eyes, ears, mouth, nose"},
    {"unit": 4, "lesson": 2, "topic": "My Body", "outcome": "Describe physical appearance: tall, short, thin, curly hair, blue eyes"},
    {"unit": 4, "lesson": 3, "topic": "My Body", "outcome": "Use He has got and She has got to describe people appearance"},
    {"unit": 4, "lesson": 4, "topic": "My Body", "outcome": "Talk about health problems: I have got a headache, stomachache, toothache, cold"},
    {"unit": 4, "lesson": 5, "topic": "My Body", "outcome": "Give simple health advice: You should rest, drink water, see a doctor"},
    {"unit": 4, "lesson": 6, "topic": "My Body", "outcome": "Review and practise Unit 4: body parts, appearance, health problems, advice"},
    {"unit": 5, "lesson": 1, "topic": "Cooking", "outcome": "Name common foods and ingredients: flour, egg, sugar, butter, milk, vegetables"},
    {"unit": 5, "lesson": 2, "topic": "Cooking", "outcome": "Understand countable and uncountable nouns with food vocabulary"},
    {"unit": 5, "lesson": 3, "topic": "Cooking", "outcome": "Use some and any correctly: Is there any milk? Yes, there is some milk"},
    {"unit": 5, "lesson": 4, "topic": "Cooking", "outcome": "Follow simple recipe instructions using imperative forms: add, mix, cut, boil, stir"},
    {"unit": 5, "lesson": 5, "topic": "Cooking", "outcome": "Talk about favourite foods and describe simple meals"},
    {"unit": 5, "lesson": 6, "topic": "Cooking", "outcome": "Review and practise Unit 5: food vocabulary, some and any, recipe instructions"},
    {"unit": 6, "lesson": 1, "topic": "Emotions", "outcome": "Name basic emotions: happy, sad, angry, scared, surprised, bored, excited, tired"},
    {"unit": 6, "lesson": 2, "topic": "Emotions", "outcome": "Ask and answer How do you feel? and respond with I feel + adjective"},
    {"unit": 6, "lesson": 3, "topic": "Emotions", "outcome": "Describe why you feel a certain way: I feel happy because it is my birthday"},
    {"unit": 6, "lesson": 4, "topic": "Emotions", "outcome": "Use adjectives to describe feelings in sentences about daily situations"},
    {"unit": 6, "lesson": 5, "topic": "Emotions", "outcome": "Talk about situations that cause emotions and use I feel... because..."},
    {"unit": 6, "lesson": 6, "topic": "Emotions", "outcome": "Review and practise Unit 6: emotions vocabulary, asking and describing feelings"},
    {"unit": 7, "lesson": 1, "topic": "Movie Time", "outcome": "Name movie genres: action, comedy, horror, animation, drama, science fiction"},
    {"unit": 7, "lesson": 2, "topic": "Movie Time", "outcome": "Express opinions about movies using I think, I believe, In my opinion"},
    {"unit": 7, "lesson": 3, "topic": "Movie Time", "outcome": "Talk about favourite actors and movies using simple present tense"},
    {"unit": 7, "lesson": 4, "topic": "Movie Time", "outcome": "Describe movie plots using simple present: The story is about, The main character"},
    {"unit": 7, "lesson": 5, "topic": "Movie Time", "outcome": "Ask and answer questions about movies: What is your favourite movie? Who is your favourite actor?"},
    {"unit": 7, "lesson": 6, "topic": "Movie Time", "outcome": "Review and practise Unit 7: movie genres, opinions, describing plots"},
    {"unit": 8, "lesson": 1, "topic": "Seasons and Weather", "outcome": "Name the four seasons: spring, summer, autumn, winter and their characteristics"},
    {"unit": 8, "lesson": 2, "topic": "Seasons and Weather", "outcome": "Describe weather conditions using It is sunny, rainy, snowy, windy, cloudy, foggy"},
    {"unit": 8, "lesson": 3, "topic": "Seasons and Weather", "outcome": "Use What is the weather like? and answer with full sentences"},
    {"unit": 8, "lesson": 4, "topic": "Seasons and Weather", "outcome": "Talk about activities in different seasons: In summer I go swimming, In winter I build snowmen"},
    {"unit": 8, "lesson": 5, "topic": "Seasons and Weather", "outcome": "Use present continuous for current weather: It is raining now, The sun is shining"},
    {"unit": 8, "lesson": 6, "topic": "Seasons and Weather", "outcome": "Review and practise Unit 8: seasons, weather vocabulary, activities"},
]

CURRICULUM_6 = [
    {"unit": 1, "lesson": 1, "topic": "Life", "outcome": "Describe daily routines using simple present: I wake up at 7, I have breakfast, I go to school"},
    {"unit": 1, "lesson": 2, "topic": "Life", "outcome": "Tell the time and talk about schedules: It is half past eight, My lesson starts at nine"},
    {"unit": 1, "lesson": 3, "topic": "Life", "outcome": "Use frequency adverbs: always, usually, often, sometimes, rarely, never"},
    {"unit": 1, "lesson": 4, "topic": "Life", "outcome": "Ask and answer about daily habits: What time do you wake up? What do you do after school?"},
    {"unit": 1, "lesson": 5, "topic": "Life", "outcome": "Describe weekend activities and compare them to weekday routines"},
    {"unit": 1, "lesson": 6, "topic": "Life", "outcome": "Review and practise Unit 1: daily routines, telling the time, frequency adverbs"},
    {"unit": 2, "lesson": 1, "topic": "Celebrations", "outcome": "Name celebrations and festivals: birthday, New Year, national holiday, Eid, harvest festival"},
    {"unit": 2, "lesson": 2, "topic": "Celebrations", "outcome": "Describe how people celebrate: They eat special food, They wear traditional clothes, They dance"},
    {"unit": 2, "lesson": 3, "topic": "Celebrations", "outcome": "Use present continuous to describe celebrations happening now: People are dancing and singing"},
    {"unit": 2, "lesson": 4, "topic": "Celebrations", "outcome": "Write and say greetings for special occasions: Happy Birthday, Happy New Year, Congratulations"},
    {"unit": 2, "lesson": 5, "topic": "Celebrations", "outcome": "Compare celebrations in Turkey and other countries using but and however"},
    {"unit": 2, "lesson": 6, "topic": "Celebrations", "outcome": "Review and practise Unit 2: festivals, celebrations vocabulary, greetings"},
    {"unit": 3, "lesson": 1, "topic": "My Environment", "outcome": "Describe natural features: mountains, rivers, forests, plains, coasts, lakes"},
    {"unit": 3, "lesson": 2, "topic": "My Environment", "outcome": "Talk about environmental problems: pollution, deforestation, litter, waste"},
    {"unit": 3, "lesson": 3, "topic": "My Environment", "outcome": "Use should and should not to give advice about protecting the environment"},
    {"unit": 3, "lesson": 4, "topic": "My Environment", "outcome": "Describe your local environment and what you love about where you live"},
    {"unit": 3, "lesson": 5, "topic": "My Environment", "outcome": "Talk about ways to help the environment: recycle, save water, plant trees, use less plastic"},
    {"unit": 3, "lesson": 6, "topic": "My Environment", "outcome": "Review and practise Unit 3: environment vocabulary, giving advice with should"},
    {"unit": 4, "lesson": 1, "topic": "Food and Restaurants", "outcome": "Read a menu and name dishes: starter, main course, dessert, drink"},
    {"unit": 4, "lesson": 2, "topic": "Food and Restaurants", "outcome": "Order food politely: I would like, Could I have, What do you recommend?"},
    {"unit": 4, "lesson": 3, "topic": "Food and Restaurants", "outcome": "Use much and many: How much sugar? How many eggs? There is not much time"},
    {"unit": 4, "lesson": 4, "topic": "Food and Restaurants", "outcome": "Describe tastes and textures: sweet, salty, sour, spicy, crunchy, soft, delicious"},
    {"unit": 4, "lesson": 5, "topic": "Food and Restaurants", "outcome": "Have a restaurant dialogue: greet customers, take orders, ask for the bill"},
    {"unit": 4, "lesson": 6, "topic": "Food and Restaurants", "outcome": "Review and practise Unit 4: restaurant vocabulary, ordering food, much and many"},
    {"unit": 5, "lesson": 1, "topic": "Sports", "outcome": "Name sports and equipment: football, basketball, swimming, tennis racket, goalkeeper"},
    {"unit": 5, "lesson": 2, "topic": "Sports", "outcome": "Talk about sports using play, go, do: I play basketball, I go swimming, I do gymnastics"},
    {"unit": 5, "lesson": 3, "topic": "Sports", "outcome": "Use simple past to talk about past sports events: They played, She scored, He won"},
    {"unit": 5, "lesson": 4, "topic": "Sports", "outcome": "Describe a sports match: The score was, The team won by two goals, It was an exciting game"},
    {"unit": 5, "lesson": 5, "topic": "Sports", "outcome": "Talk about your favourite sports star and why you admire them"},
    {"unit": 5, "lesson": 6, "topic": "Sports", "outcome": "Review and practise Unit 5: sports vocabulary, play/go/do, simple past"},
    {"unit": 6, "lesson": 1, "topic": "Occupations", "outcome": "Name jobs and say what people do: A doctor treats patients, A teacher teaches students"},
    {"unit": 6, "lesson": 2, "topic": "Occupations", "outcome": "Talk about workplace and tools: A chef works in a kitchen and uses knives and pans"},
    {"unit": 6, "lesson": 3, "topic": "Occupations", "outcome": "Use want to be and would like to be to talk about future jobs: I want to be an engineer"},
    {"unit": 6, "lesson": 4, "topic": "Occupations", "outcome": "Describe skills and qualities needed for jobs: You need to be patient, creative, hardworking"},
    {"unit": 6, "lesson": 5, "topic": "Occupations", "outcome": "Ask and answer about jobs: What does your mother do? Where does she work?"},
    {"unit": 6, "lesson": 6, "topic": "Occupations", "outcome": "Review and practise Unit 6: jobs vocabulary, describing roles, future plans"},
    {"unit": 7, "lesson": 1, "topic": "Movies", "outcome": "Name film genres and describe them: An action film is exciting, A comedy makes you laugh"},
    {"unit": 7, "lesson": 2, "topic": "Movies", "outcome": "Give opinions about films: I think it was brilliant, I found it boring, The acting was great"},
    {"unit": 7, "lesson": 3, "topic": "Movies", "outcome": "Use comparative adjectives: more exciting than, funnier than, scarier than"},
    {"unit": 7, "lesson": 4, "topic": "Movies", "outcome": "Describe a film plot using past simple: The story was about, The hero saved, In the end"},
    {"unit": 7, "lesson": 5, "topic": "Movies", "outcome": "Recommend a film and explain why someone should watch it"},
    {"unit": 7, "lesson": 6, "topic": "Movies", "outcome": "Review and practise Unit 7: film genres, opinions, comparative adjectives"},
    {"unit": 8, "lesson": 1, "topic": "Music", "outcome": "Name music genres: pop, rock, classical, jazz, folk, hip hop, electronic"},
    {"unit": 8, "lesson": 2, "topic": "Music", "outcome": "Name instruments and say who plays them: a guitarist plays the guitar, a pianist plays the piano"},
    {"unit": 8, "lesson": 3, "topic": "Music", "outcome": "Talk about music preferences using like, love, prefer, cannot stand"},
    {"unit": 8, "lesson": 4, "topic": "Music", "outcome": "Use superlative adjectives: the best song, the most popular band, the greatest musician"},
    {"unit": 8, "lesson": 5, "topic": "Music", "outcome": "Describe your favourite musician or band and explain what makes their music special"},
    {"unit": 8, "lesson": 6, "topic": "Music", "outcome": "Review and practise Unit 8: music genres, instruments, superlatives"},
]